# Generated by Django 5.2 on 2025-04-13 03:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wines", "0002_grape_wine_grape"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wine",
            old_name="grape",
            new_name="grapes",
        ),
    ]
