# Generated by Django 4.1.2 on 2025-04-13 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wines", "0003_rename_grape_wine_grapes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="winetype",
            old_name="name",
            new_name="type",
        ),
        migrations.AlterField(
            model_name="grape",
            name="name",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="grape",
            name="wine_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grapeS",
                to="wines.winetype",
            ),
        ),
    ]
