# Generated by Django 4.1.2 on 2025-05-30 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wines", "0004_rename_name_winetype_type_alter_grape_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grape",
            name="wine_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grapes",
                to="wines.winetype",
            ),
        ),
    ]
