# Generated by Django 4.1.2 on 2025-06-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wines", "0005_alter_grape_wine_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grape",
            name="wine_type",
            field=models.CharField(
                choices=[
                    ("white", "white"),
                    ("red", "red"),
                    ("sparkling", "sparkling"),
                    ("orange", "orange"),
                    ("dessert", "dessert"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="wine",
            name="wine_type",
            field=models.CharField(
                choices=[
                    ("white", "white"),
                    ("red", "red"),
                    ("sparkling", "sparkling"),
                    ("orange", "orange"),
                    ("dessert", "dessert"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="WineType",
        ),
    ]
