# Generated by Django 4.1.2 on 2025-06-13 09:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wines", "0006_alter_grape_wine_type_alter_wine_wine_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="grape",
            name="wine_type",
        ),
    ]
