# Generated by Django 4.1.2 on 2025-08-09 03:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wines", "0007_remove_grape_wine_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="wine",
            name="imageURL",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
