# Generated by Django 4.1.2 on 2025-08-09 03:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wines", "0008_wine_imageurl"),
    ]

    operations = [
        migrations.AddField(
            model_name="wine",
            name="region",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
