# Generated by Django 4.1.2 on 2025-08-09 03:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wines", "0009_wine_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="wine",
            name="notes",
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
