# Generated by Django 4.1.2 on 2025-12-15 02:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wines", "0010_wine_notes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wine",
            name="restaurant",
        ),
    ]
