# Generated by Django 4.1.2 on 2026-05-30 23:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wines", "0011_remove_wine_restaurant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wine",
            name="wine_type",
            field=models.CharField(
                choices=[
                    ("white", "white"),
                    ("red", "red"),
                    ("sparkling", "sparkling"),
                    ("orange", "orange"),
                    ("dessert", "dessert"),
                ],
                db_index=True,
                max_length=20,
                null=True,
            ),
        ),
    ]
