# Generated by Django 5.2 on 2025-04-13 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventories", "0001_initial"),
        ("restaurants", "0001_initial"),
        ("wines", "0003_rename_grape_wine_grapes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventory",
                to="restaurants.restaurant",
            ),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="wine",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventory",
                to="wines.wine",
            ),
        ),
    ]
