# Generated by Django 4.1.2 on 2025-05-30 04:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventories", "0002_alter_inventory_restaurant_alter_inventory_wine"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="image",
            field=models.JSONField(null=True),
        ),
    ]
