# Generated by Django 4.1.2 on 2025-05-30 05:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventories", "0003_inventory_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="image",
            field=models.URLField(blank=True, null=True),
        ),
    ]
