# Generated by Django 4.1.2 on 2025-12-13 22:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventories", "0004_alter_inventory_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="profit_margin",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
