# Generated by Django 4.1.2 on 2025-12-14 23:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventories", "0005_inventory_profit_margin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventory",
            name="image",
        ),
    ]
