# Generated by Django 4.1.2 on 2026-06-06 19:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wines", "0012_alter_wine_wine_type"),
        ("restaurants", "0002_update_restaurant_address_fields"),
        ("inventories", "0006_remove_inventory_image"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="inventory",
            unique_together={("wine", "restaurant")},
        ),
    ]
