# Generated by Django 4.1.2 on 2026-06-06 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventories", "0008_remove_inventory_profit_margin"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="inventory",
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name="inventory",
            index=models.Index(
                fields=["restaurant", "wine"], name="inventory_restaurant_wine_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="inventory",
            constraint=models.UniqueConstraint(
                fields=("wine", "restaurant"), name="unique_inventory_wine_restaurant"
            ),
        ),
    ]
